"""Adapter for Rugby-Data's public Premiership season JSON.

The source provides one season JSON containing match records. The acquisition
script reproducibly splits it into one raw JSON file per original match record so
the common pipeline can incrementally process a newly added/changed match.
"""

from __future__ import annotations

import json
import math
import re
from datetime import datetime
from pathlib import Path
from typing import Any

from rugby_analysis.adapters.base import EventDataAdapter
from rugby_analysis.core.schema import CanonicalEvent


SOURCE_NAME = "rugby_data_premiership_2024_2025"
SOURCE_REPOSITORY = "https://github.com/transientlunatic/Rugby-Data"


def slug(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", value.casefold()).strip("_")


def match_id_from_record(record: dict[str, Any]) -> str:
    home = str(record.get("home", {}).get("team", "unknown_home"))
    away = str(record.get("away", {}).get("team", "unknown_away"))
    date = str(record.get("date", "undated"))[:10]
    return f"rugbydata_{date}_{slug(home)}_vs_{slug(away)}"


def event_outcome(raw_type: str, value: int | float | None) -> str | None:
    if raw_type.casefold().startswith("missed"):
        return "missed"
    if value is not None and value > 0:
        return "scored"
    return None


def numeric_value(value: object) -> float | None:
    """Return a finite numeric source value without manufacturing a default."""
    if isinstance(value, bool):
        return None
    if isinstance(value, (int, float)):
        numeric = float(value)
        return numeric if math.isfinite(numeric) else None
    try:
        numeric = float(str(value))
        return numeric if math.isfinite(numeric) else None
    except (TypeError, ValueError):
        return None


class RugbyDataJsonAdapter(EventDataAdapter):
    """Map real score/card/substitution timeline records into canonical events."""

    source_name = SOURCE_NAME

    def __init__(self, raw_root: Path, manifest_path: Path | None = None) -> None:
        self.raw_root = Path(raw_root)
        self.manifest_path = manifest_path or self.raw_root.parent / "source_manifest.json"
        self._last_warnings: list[str] = []

    def discover_files(self, raw_root: Path | None = None) -> list[Path]:
        directory = Path(raw_root or self.raw_root)
        return sorted(directory.glob("*.json"), key=lambda path: path.name)

    @staticmethod
    def match_id_for_file(file_path: Path) -> str:
        """Return the acquisition-assigned ID without reopening raw JSON.

        ``download_data.py`` names each split source record with the same stable
        ID generated by :func:`match_id_from_record`. This lets the pipeline
        identify its output before ``normalize_file`` performs the only raw JSON
        parse for that match.
        """
        return file_path.stem

    def normalize_file(self, file_path: Path) -> list[CanonicalEvent]:
        record = json.loads(file_path.read_text(encoding="utf-8"))
        match_id = match_id_from_record(record)
        home = dict(record.get("home") or {})
        away = dict(record.get("away") or {})
        common_metadata = {
            "source_repository": SOURCE_REPOSITORY,
            "source_file": file_path.name,
            "match_date": record.get("date"),
            "fixture_label": f"{str(record.get('date', ''))[:10]}: {home.get('team', 'Unknown')} vs {away.get('team', 'Unknown')}",
            "round": record.get("round"),
            "round_type": record.get("round_type"),
            "stadium": record.get("stadium"),
            "attendance": record.get("attendance"),
            "home_team": home.get("team"),
            "away_team": away.get("team"),
            "home_final_score": home.get("score"),
            "away_final_score": away.get("score"),
        }
        pending: list[dict[str, Any]] = []
        missing_player_events = 0
        score_value_totals: dict[str, float] = {"home": 0.0, "away": 0.0}
        published_final_scores: dict[str, float | None] = {
            "home": numeric_value(home.get("score")),
            "away": numeric_value(away.get("score")),
        }
        for side_name, team_record, opponent_record in (("home", home, away), ("away", away, home)):
            team_name = team_record.get("team")
            opponent_name = opponent_record.get("team")
            for source_index, score in enumerate(team_record.get("scores") or []):
                raw_type = str(score.get("type") or "unknown_score_event")
                source_value = numeric_value(score.get("value"))
                if source_value is not None:
                    score_value_totals[side_name] += source_value
                minute = score.get("minute")
                timestamp_seconds = float(minute) * 60 if isinstance(minute, (int, float)) else None
                player_name = score.get("player")
                if not player_name:
                    missing_player_events += 1
                pending.append(
                    {
                        "event_id": f"{match_id}_{side_name}_score_{source_index}",
                        "timestamp_seconds": timestamp_seconds,
                        "team_name": team_name,
                        "opponent_name": opponent_name,
                        "player_name": player_name,
                        "event_type": slug(raw_type) or "unknown_score_event",
                        "outcome": event_outcome(raw_type, source_value),
                        "metadata": {
                            **common_metadata,
                            "event_category": "scoring",
                            "team_side": side_name,
                            "source_score_type": raw_type,
                            "score_value": source_value,
                            "source_minute": minute,
                        },
                    }
                )
            for shirt_number, player in (team_record.get("lineup") or {}).items():
                player_name = player.get("name")
                for occurrence_index, minute in enumerate(player.get("on") or []):
                    # A minute-zero entry identifies a starter, not a substitution event.
                    if isinstance(minute, (int, float)) and minute > 0:
                        pending.append(
                            {
                                "event_id": f"{match_id}_{side_name}_{shirt_number}_on_{occurrence_index}",
                                "timestamp_seconds": float(minute) * 60,
                                "team_name": team_name,
                                "opponent_name": opponent_name,
                                "player_name": player_name,
                                "event_type": "substitution_on",
                                "outcome": None,
                                "metadata": {**common_metadata, "event_category": "lineup", "team_side": side_name, "shirt_number": shirt_number, "source_minute": minute},
                            }
                        )
                for occurrence_index, minute in enumerate(player.get("off") or []):
                    if isinstance(minute, (int, float)):
                        pending.append(
                            {
                                "event_id": f"{match_id}_{side_name}_{shirt_number}_off_{occurrence_index}",
                                "timestamp_seconds": float(minute) * 60,
                                "team_name": team_name,
                                "opponent_name": opponent_name,
                                "player_name": player_name,
                                "event_type": "substitution_off",
                                "outcome": None,
                                "metadata": {**common_metadata, "event_category": "lineup", "team_side": side_name, "shirt_number": shirt_number, "source_minute": minute},
                            }
                        )
                for card_type, source_key in (("yellow_card", "yellows"), ("red_card", "reds")):
                    for occurrence_index, minute in enumerate(player.get(source_key) or []):
                        if isinstance(minute, (int, float)):
                            pending.append(
                                {
                                    "event_id": f"{match_id}_{side_name}_{shirt_number}_{card_type}_{occurrence_index}",
                                    "timestamp_seconds": float(minute) * 60,
                                    "team_name": team_name,
                                    "opponent_name": opponent_name,
                                    "player_name": player_name,
                                    "event_type": card_type,
                                    "outcome": "recorded",
                                    "metadata": {**common_metadata, "event_category": "discipline", "team_side": side_name, "shirt_number": shirt_number, "source_minute": minute},
                                }
                            )

        pending.sort(key=lambda item: (item["timestamp_seconds"] is None, item["timestamp_seconds"] or 0, item["event_id"]))
        self._last_warnings = []
        if not pending and any(score is not None for score in published_final_scores.values()):
            self._last_warnings.append(
                "Published final score is present but the source supplies no score, lineup or card timeline records."
            )
        for side_name, source_total in score_value_totals.items():
            published_total = published_final_scores[side_name]
            if published_total is not None and source_total != published_total:
                self._last_warnings.append(
                    f"{side_name.title()} source score-event values total {source_total:g}, but published final score is "
                    f"{published_total:g}; final-score and event-value metrics remain separate."
                )
        if missing_player_events:
            self._last_warnings.append(f"{missing_player_events} scoring event(s) had no player name in the public source.")
        return [
            CanonicalEvent(
                source=self.source_name,
                match_id=match_id,
                event_id=item["event_id"],
                sequence_index=index,
                timestamp_seconds=item["timestamp_seconds"],
                team_name=item["team_name"],
                opponent_name=item["opponent_name"],
                player_name=item["player_name"],
                event_type=item["event_type"],
                outcome=item["outcome"],
                metadata=item["metadata"],
            )
            for index, item in enumerate(pending)
        ]

    def validate(self, events: list[CanonicalEvent]) -> list[str]:
        warnings = super().validate(events)
        if events and any(event.team_name is None for event in events):
            warnings.append("At least one public event has no team attribution.")
        return [*warnings, *self._last_warnings]
