"""Synthetic partner-schema rows used without copying private source data into tests."""

from __future__ import annotations

import pandas as pd
import pytest


@pytest.fixture
def partner_rows() -> pd.DataFrame:
    """Return representative source-style records for the three Week 11 modules."""

    return pd.DataFrame(
        [
            {
                "ID": 1,
                "FXID": 949231,
                "PLID": 10,
                "playerName": "Kicker One",
                "teamName": "NSW Waratahs",
                "ps_timestamp": 12.5,
                "ps_endstamp": 14.0,
                "MatchTime": 17,
                "period": 1,
                "x_coord": 25,
                "y_coord": 30,
                "x_coord_end": 65,
                "y_coord_end": 22,
                "actionName": "Kick",
                "ActionTypeName": "Box",
                "ActionResultName": "Caught Full",
                "qualifier5Name": "Kick Receipt Contested",
                "qualifier6Name": None,
            },
            {
                "ID": 2,
                "FXID": 949231,
                "PLID": 11,
                "playerName": "Kicker Two",
                "teamName": "NSW Waratahs",
                "ps_timestamp": 41.0,
                "ps_endstamp": 42.0,
                "MatchTime": 4328,
                "period": 1,
                "x_coord": 82,
                "y_coord": 34,
                "x_coord_end": 100,
                "y_coord_end": 40,
                "actionName": "Kick",
                "ActionTypeName": "Touch Kick",
                "ActionResultName": "Kick in Touch (Full)",
                "qualifier5Name": "Kick Receipt Not Contested",
                "qualifier6Name": None,
            },
            {
                "ID": 3,
                "FXID": 949231,
                "PLID": 9,
                "playerName": "Halfback",
                "teamName": "NSW Waratahs",
                "ps_timestamp": 50.0,
                "ps_endstamp": 51.0,
                "MatchTime": 4400,
                "period": 1,
                "x_coord": 12,
                "y_coord": 20,
                "x_coord_end": 14,
                "y_coord_end": 20,
                "actionName": "Playmaker Options",
                "ActionTypeName": "Halfback at Breakdown",
                "ActionResultName": "Playmaker Option - Pass",
                "qualifier5Name": None,
                "qualifier6Name": None,
            },
            {
                "ID": 4,
                "FXID": 949231,
                "PLID": 12,
                "playerName": "Centre",
                "teamName": "NSW Waratahs",
                "ps_timestamp": 55.0,
                "ps_endstamp": 56.0,
                "MatchTime": 4405,
                "period": 1,
                "x_coord": 62,
                "y_coord": 24,
                "x_coord_end": 67,
                "y_coord_end": 24,
                "actionName": "Playmaker Options",
                "ActionTypeName": "First Receiver",
                "ActionResultName": "Playmaker Option - Carry",
                "qualifier5Name": None,
                "qualifier6Name": None,
            },
            {
                "ID": 5,
                "FXID": 949231,
                "PLID": 6,
                "playerName": "Tackler One",
                "teamName": "NSW Waratahs",
                "ps_timestamp": 70.0,
                "ps_endstamp": 71.0,
                "MatchTime": 4510,
                "period": 1,
                "x_coord": 48,
                "y_coord": 31,
                "x_coord_end": 48,
                "y_coord_end": 31,
                "actionName": "Tackle",
                "ActionTypeName": "Line",
                "ActionResultName": "Complete",
                "qualifier5Name": "1st Tackler",
                "qualifier6Name": "Upper Torso",
            },
            {
                "ID": 6,
                "FXID": 949231,
                "PLID": 7,
                "playerName": "Tackler Two",
                "teamName": "NSW Waratahs",
                "ps_timestamp": 75.0,
                "ps_endstamp": 76.0,
                "MatchTime": 4515,
                "period": 1,
                "x_coord": 104,
                "y_coord": 35,
                "x_coord_end": 104,
                "y_coord_end": 35,
                "actionName": "Tackle",
                "ActionTypeName": "Edge",
                "ActionResultName": "Passive",
                "qualifier5Name": "1st Tackler",
                "qualifier6Name": "Legs",
            },
            {
                "ID": 7,
                "FXID": 949231,
                "PLID": 8,
                "playerName": "Tackler Two",
                "teamName": "NSW Waratahs",
                "ps_timestamp": 80.0,
                "ps_endstamp": 81.0,
                "MatchTime": 4520,
                "period": 1,
                "x_coord": 54,
                "y_coord": 35,
                "x_coord_end": 54,
                "y_coord_end": 35,
                "actionName": "Missed Tackle",
                "ActionTypeName": "Stepped",
                "ActionResultName": "Clean Break",
                "qualifier5Name": None,
                "qualifier6Name": None,
            },
        ]
    )
